[build]
functions = "/functions"
command = "npm run"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/dashboard"

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/login"
[[redirects]]
  from = "signup"
  to = "/.netlify/functions/signup"

[[redirects]]
  from = "/data"
  to = "/.netlify/functions/data"
  
[[headers]]
  for = ".netlify/functions/login"
  [headers.values]
   Content-Type = "application/json"
   Key = "Content-Type"
   Value = "application/json"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
